dir:
	gcc -Wall -o main find_readdir.c
	./main ../../ mtime = 0 
	./main ../../ mtime + 7 
	./main ../../ atime - 3 

nftw:
	gcc -Wall -o main find_nftw.c
	./main ../../ mtime + 7 -1
	./main ../../ mtime + 7 1
	./main ../../ atime - 3 2